In [6]:
import pandas as pd
import seaborn as sns
import numpy as np
import os
os.getcwd()

'C:\\Users\\Kartik\\Desktop\\Lab6'

In [26]:
data = pd.read_csv('anneal.data')

In [27]:
test = pd.read_csv('anneal.test')

In [28]:
data

,?,C,A,08,00,?.1,S,?.2,000,?.3,...,?.22,?.23,COIL,0.700,0610.0,0000,?.24,0000.1,?.25,3
0,?,C,R,0,0,?,S,2,0,?,...,?,?,COIL,3.200,610.0,0,?,0,?,3
1,?,C,R,0,0,?,S,2,0,?,...,?,?,SHEET,0.700,1300.0,762,?,0,?,3
2,?,C,A,0,60,T,?,?,0,?,...,?,?,COIL,2.801,385.1,0,?,0,?,3
3,?,C,A,0,60,T,?,?,0,?,...,?,?,SHEET,0.801,255.0,269,?,0,?,3
4,?,C,A,0,45,?,S,?,0,?,...,?,?,COIL,1.600,610.0,0,?,0,?,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,?,C,A,0,50,T,?,?,0,?,...,?,?,COIL,1.001,50.0,0,Y,0,?,3
793,?,C,?,0,0,?,S,1,0,?,...,?,?,SHEET,0.699,1300.0,4880,?,0,?,3
794,?,C,A,0,0,?,S,2,0,?,...,?,?,COIL,0.400,609.9,0,?,0,?,3
795,?,C,A,0,0,?,S,2,0,?,...,?,?,SHEET,3.200,610.0,4880,?,0,?,3
796,?,C,R,0,0,?,S,2,0,?,...,?,?,SHEET,1.599,1500.0,4170,?,0,?,2

In [29]:
test

,?,C,A,00,45,?.1,S,?.2,000,?.3,...,?.22,?.23,COIL,1.600,0610.0,0000,?.24,0000.1,?.25,3
0,?,C,A,0,0,?,S,3,0,N,...,?,?,COIL,0.699,609.9,0,?,0,?,3
1,ZS,C,A,0,85,T,?,?,0,?,...,?,?,SHEET,0.400,610.0,762,?,0,?,U
2,ZS,C,A,0,50,T,?,?,0,?,...,?,?,COIL,0.400,610.0,0,?,0,?,3
3,?,C,A,0,0,?,S,2,0,?,...,?,?,COIL,0.699,1320.0,0,?,0,?,3
4,TN,C,?,0,0,?,A,1,0,?,...,?,?,COIL,0.800,50.0,0,?,0,?,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,?,C,R,0,0,?,S,3,0,?,...,?,?,SHEET,1.599,610.0,762,?,0,?,2
95,?,C,R,0,0,?,S,3,0,?,...,?,?,SHEET,1.601,830.0,880,?,0,?,2
96,?,C,V,0,0,?,S,2,0,?,...,?,?,SHEET,1.599,150.0,762,?,0,?,2
97,?,C,A,0,85,T,?,?,0,?,...,?,?,COIL,0.400,20.0,0,?,0,?,U
98,?,C,A,0,85,T,?,?,0,?,...,?,?,COIL,4.000,610.0,0,?,500,?,U